### ISSUE TITLE
0.options[0].type: This field is required

### ISSUE THREAD

**Issue by d3n972** [KartikeSingh/discord-slash-command-handler#3]
Hi, I currently trying to implement a basic slash command support in my bot, but it's seems like the lib doesn't add the type field to the api request, despite I supplied it.

```
//in the command definition
options: [
        {
            name: "test",
            description: "description of the argument",
            required: true,
            type: "string"
        }
    ],
    
```
```

//from the api request
 options: [
          {
            type: undefined,
            name: 'test',
            description: 'description of the argument',
            required: true,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined
          }
        ],
    ```

**Comment by KartikeSingh** [comment]
I see, I think because of my habit of using integer instead of string type I forgot to implement auto string to int convertor, thank you very much for this information.
I will fix it and push the update real quick.
for now you can use integer value from [here](https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-option-type).

**Comment by KartikeSingh** [comment]
alright, after a bit of testing I found out that we do have a string to integer type convertor but it is way to inefficient, So it only fixes top level types, but i fixed it.
After a bit of testing I will publish it.

**Comment by KartikeSingh** [comment]
Hello @d3n972,
I published the new package
you can install it via `npm i discord-slash-command-handler@3.1.1`
and you can read the docs [here](https://www.npmjs.com/package/discord-slash-command-handler/v/3.1.1)
